CREATE TABLE create_table_log (
id NUMBER GENERATED BY DEFAULT AS IDENTITY,
usuario VARCHAR(30),
nombre_tabla VARCHAR(30),
propietario_objeto VARCHAR(30),
fecha_creacion DATE,
PRIMARY KEY(id)
);

/
CREATE OR REPLACE TRIGGER registro_tablas_usuarios
AFTER CREATE ON SCHEMA
BEGIN

IF ORA_DICT_OBJ_TYPE = 'TABLE' THEN
    INSERT INTO  create_table_log (usuario, nombre_tabla, propietario_objeto, fecha_creacion)
    VALUES (USER,ORA_DICT_OBJ_NAME,ORA_DICT_OBJ_OWNER,SYSDATE);
END IF;

END;
/
CREATE TABLE test (
   id NUMBER
);
CREATE SEQUENCE test2;

CREATE TABLE test3 (
   id NUMBER
);

CREATE TYPE test4 AS OBJECT(
    texto VARCHAR(2)
);
/
SELECT * FROM create_table_log;
/
DROP TABLE create_table_log;
DROP TABLE test;
DROP SEQUENCE test2;
DROP TABLE test3;
DROP TYPE test4;
DROP TRIGGER registro_tablas_usuarios;