---- Lecturas autorizadas
SELECT * FROM APLICACIONES_DELIVERY;
SELECT * FROM PLANES_DE_SERVICIO;
SELECT * FROM UBICACIONES_APLICABLES;
SELECT * FROM CONTRATOS;
SELECT * FROM EMPRESAS;
SELECT * FROM SUCURSALES;
SELECT * FROM ALMACENES;
SELECT * FROM EVENTOS;
SELECT * FROM PRODUCTOS;
SELECT * FROM PEDIDOS;
SELECT * FROM DETALLES;
SELECT * FROM RUTAS;
SELECT * FROM GARAJES;
SELECT * FROM UNIDADES_DE_TRANSPORTE;
SELECT * FROM TIPOS_DE_UNIDADES;
SELECT * FROM REGISTROS;
SELECT * FROM USUARIOS;
SELECT * FROM DIRECCIONES;
SELECT * FROM ZONAS;
SELECT * FROM MUNICIPIOS;
SELECT * FROM ESTADOS;

---- Lecturas no autorizadas
SELECT * FROM REGISTRO_DE_MANTENIMIENTO;

---- CREACIONES AUTORIZADAS

-- crear producto
INSERT INTO PRODUCTOS VALUES (1, 5, DEFAULT, 'Sushi especial', 1.74, 0, 'Ración mixta de sushi');

-- crear un evento
INSERT INTO eventos VALUES (12,12,DEFAULT,rango_tiempo(sysdate),TRUNC(dbms_random.VALUE(5,20),2));

--- CREACIONES NO AUTORIZADAS

-- insertar un plan de servicio
INSERT INTO planes_de_servicio VALUES
(17,DEFAULT,RANGO_TIEMPO(SYSDATE,TO_DATE('01/01/2022', 'dd/mm/yyyy')),250,1400,'SEMESTRAL',NULL);

-- insertar un contrato
INSERT INTO contratos VALUES (2, 5, 25,DEFAULT, RANGO_TIEMPO(TO_DATE('2020-12-08','yyyy-mm-dd'),TO_DATE('2021-11-04','yyyy-mm-dd')), 0.00, null);

--- UPDATES AUTORIZADO

-- cambiar el porcentaje descuento de un evento
UPDATE eventos SET porcentaje_descuento=30 WHERE ID = 2;

-- cambiar el nombre de un producto
UPDATE PRODUCTOS SET nombre='galletas light' WHERE ID = 2;


--- UPDATES NO AUTORIZADO
-- update en tipos de unidades
UPDATE TIPOS_DE_UNIDADES SET velocidad_media = 66 WHERE ID = 3;
--- update en planes de servicio
UPDATE PLANES_DE_SERVICIO SET precio = 100 WHERE ID = 2;


-- DELETES AUTORIZADOS
DELETE FROM EVENTOS WHERE ID =4;

-- DELETES NO AUTORIZADOS
-- borrar una rutas
DELETE FROM RUTAS WHERE ID =1;
-- borrar garaje
DELETE FROM garajes WHERE ID=2;
