---------- LECTURAS AUTORIZADAS
SELECT * FROM C##TESTUSER.APLICACIONES_DELIVERY;
SELECT * FROM C##TESTUSER.PLANES_DE_SERVICIO;
SELECT * FROM C##TESTUSER.UBICACIONES_APLICABLES;
SELECT * FROM C##TESTUSER.CONTRATOS;
SELECT * FROM C##TESTUSER.EMPRESAS;
SELECT * FROM C##TESTUSER.SUCURSALES;
SELECT * FROM C##TESTUSER.PRODUCTOS;
SELECT * FROM C##TESTUSER.PEDIDOS;
SELECT * FROM C##TESTUSER.DETALLES;
SELECT * FROM C##TESTUSER.RUTAS;
SELECT * FROM C##TESTUSER.GARAJES;
SELECT * FROM C##TESTUSER.UNIDADES_DE_TRANSPORTE;
SELECT * FROM C##TESTUSER.REGISTRO_DE_MANTENIMIENTO;
SELECT * FROM C##TESTUSER.TIPOS_DE_UNIDADES;
SELECT * FROM C##TESTUSER.REGISTROS;
SELECT * FROM C##TESTUSER.USUARIOS;
SELECT * FROM C##TESTUSER.DIRECCIONES;
SELECT * FROM C##TESTUSER.ZONAS;
SELECT * FROM C##TESTUSER.MUNICIPIOS;
SELECT * FROM C##TESTUSER.ESTADOS;

----- LECTURAS NO AUTORIZADAS
SELECT * FROM C##TESTUSER.ALMACENES;
SELECT * FROM C##TESTUSER.EVENTOS;

---- ALGUNAS CREACIONES AUTORIZADAS
-- crear un usuario
CALL C##TESTUSER.INSERTAR_USUARIO('John', null, 'Perez', 'Cor', 'V', 26131344, 'jphnp0@4shared.com','hombre1.jpg');
commit;
-- crear una unidad de transporte
INSERT INTO C##TESTUSER.unidades_de_transporte VALUES (1,17,17,DEFAULT,'NUE-65v','OPERATIVA');
commit;


---- ALGUNAS CREACIONES NO AUTORIZADAS
-- crear una sucursal de empresa
INSERT INTO C##TESTUSER.sucursales VALUES (24,335,1117,1,DEFAULT,C##TESTUSER.UBICACION(10.509909,-66.913139,SYSDATE));


-- crear un nuevo sector de comercio
INSERT INTO C##TESTUSER.SECTORES_DE_COMERCIO VALUES (DEFAULT, 'Nuevo Sector');

---- ALGUNOS UPDATES AUTORIZADOS

-- cambiar precio de plan de servicio
UPDATE C##TESTUSER.PLANES_DE_SERVICIO SET precio = 666 WHERE ID = 1;
commit;

-- cambiar porcentaje de descuento de un contrato
UPDATE C##TESTUSER.CONTRATOS SET porcentaje_descuento = 10 WHERE ID = 1;
commit;

---- ALGUNOS UPDATES NO AUTORIZADOS

-- cambiar el sector de una empresa
UPDATE C##TESTUSER.EMPRESAS SET id_sector = 6 WHERE ID = 1;

-- cambiar el nombre de un producto de un aliado comercial
UPDATE C##TESTUSER.PRODUCTOS SET nombre='galletas de pollo' WHERE ID = 1;

---- DELETE AUTORIZADO

--- borrar un detalle
DELETE FROM C##TESTUSER.DETALLES where ID = 6;

---- DELETES NO AUTORIZADO

--- borrar una aplicacion delivery
DELETE FROM C##TESTUSER.APLICACIONES_DELIVERY where ID = 6;