---------- LECTURAS AUTORIZADAS
SELECT * FROM C##TESTUSER.APLICACIONES_DELIVERY;
SELECT * FROM C##TESTUSER.EMPRESAS;
SELECT * FROM C##TESTUSER.SUCURSALES;
SELECT * FROM C##TESTUSER.PRODUCTOS;
SELECT * FROM C##TESTUSER.PEDIDOS;
SELECT * FROM C##TESTUSER.DETALLES;
SELECT * FROM C##TESTUSER.RUTAS;
SELECT * FROM C##TESTUSER.GARAJES;
SELECT * FROM C##TESTUSER.UNIDADES_DE_TRANSPORTE;
SELECT * FROM C##TESTUSER.REGISTRO_DE_MANTENIMIENTO;
SELECT * FROM C##TESTUSER.TIPOS_DE_UNIDADES;
SELECT * FROM C##TESTUSER.USUARIOS;
SELECT * FROM C##TESTUSER.DIRECCIONES;
SELECT * FROM C##TESTUSER.ZONAS;
SELECT * FROM C##TESTUSER.MUNICIPIOS;
SELECT * FROM C##TESTUSER.ESTADOS;


---------- ALGUNAS LECTURAS NO AUTORIZADAS
SELECT * FROM C##TESTUSER.PLANES_DE_SERVICIO;
SELECT * FROM C##TESTUSER.UBICACIONES_APLICABLES;
SELECT * FROM C##TESTUSER.CONTRATOS;
SELECT * FROM C##TESTUSER.ALMACENES;
SELECT * FROM C##TESTUSER.EVENTOS;
SELECT * FROM C##TESTUSER.REGISTROS;

----------- ALGUNAS CREACIONES NO AUTORIZADAS

-- crear un garaje
INSERT INTO C##TESTUSER.garajes VALUES (1,DEFAULT,C##TESTUSER.UBICACION(10.511941,-66.911546,SYSDATE),24,335,1117);

-- insertar una sucursal
INSERT INTO  C##TESTUSER.sucursales VALUES (24,335,1117,1,DEFAULT,C##TESTUSER.UBICACION(10.509909,-66.913139,SYSDATE));

-------------- ALGUNOS UPDATE NO AUTORIZADOS

-- update en tipos de unidades
UPDATE C##TESTUSER.TIPOS_DE_UNIDADES SET velocidad_media = 66 WHERE ID = 3;
--- update en planes de servicio
UPDATE C##TESTUSER.PLANES_DE_SERVICIO SET precio = 100 WHERE ID = 2;

------------- ALGUNOS DELETE NO AUTORIZADOS

-- borrar un estado
DELETE FROM C##TESTUSER.ESTADOS WHERE ID = 2;

-- borrar una direccion
DELETE FROM C##TESTUSER.DIRECCIONES WHERE ID = 13;
