---- Lecturas autorizadas
SELECT * FROM C##TESTUSER.APLICACIONES_DELIVERY;
SELECT * FROM C##TESTUSER.PLANES_DE_SERVICIO;
SELECT * FROM C##TESTUSER.UBICACIONES_APLICABLES;
SELECT * FROM C##TESTUSER.CONTRATOS;
SELECT * FROM C##TESTUSER.EMPRESAS;
SELECT * FROM C##TESTUSER.SUCURSALES;
SELECT * FROM C##TESTUSER.ALMACENES;
SELECT * FROM C##TESTUSER.EVENTOS;
SELECT * FROM C##TESTUSER.PRODUCTOS;
SELECT * FROM C##TESTUSER.PEDIDOS;
SELECT * FROM C##TESTUSER.DETALLES;
SELECT * FROM C##TESTUSER.RUTAS;
SELECT * FROM C##TESTUSER.GARAJES;
SELECT * FROM C##TESTUSER.UNIDADES_DE_TRANSPORTE;
SELECT * FROM C##TESTUSER.TIPOS_DE_UNIDADES;
SELECT * FROM C##TESTUSER.REGISTROS;
SELECT * FROM C##TESTUSER.USUARIOS;
SELECT * FROM C##TESTUSER.DIRECCIONES;
SELECT * FROM C##TESTUSER.ZONAS;
SELECT * FROM C##TESTUSER.MUNICIPIOS;
SELECT * FROM C##TESTUSER.ESTADOS;

---- Lecturas no autorizadas
SELECT * FROM C##TESTUSER.REGISTRO_DE_MANTENIMIENTO;

---- CREACIONES AUTORIZADAS

-- crear producto
INSERT INTO C##TESTUSER.PRODUCTOS VALUES (1, 5, DEFAULT, 'Sushi especial', 1.74, 0, 'Ración mixta de sushi');

-- crear un evento


---