---- Lecturas autorizadas
SELECT * FROM APLICACIONES_DELIVERY;
SELECT * FROM PLANES_DE_SERVICIO;
SELECT * FROM UBICACIONES_APLICABLES;
SELECT * FROM CONTRATOS;
SELECT * FROM EMPRESAS;
SELECT * FROM SUCURSALES;
SELECT * FROM ALMACENES;
SELECT * FROM EVENTOS;
SELECT * FROM PRODUCTOS;
SELECT * FROM PEDIDOS;
SELECT * FROM DETALLES;
SELECT * FROM RUTAS;
SELECT * FROM GARAJES;
SELECT * FROM UNIDADES_DE_TRANSPORTE;
SELECT * FROM TIPOS_DE_UNIDADES;
SELECT * FROM REGISTROS;
SELECT * FROM USUARIOS;
SELECT * FROM DIRECCIONES;
SELECT * FROM ZONAS;
SELECT * FROM MUNICIPIOS;
SELECT * FROM ESTADOS;

---- Lecturas no autorizadas
SELECT * FROM REGISTRO_DE_MANTENIMIENTO;


--- CREACIONES AUTORIZADAS
-- crear una sucursal
INSERT INTO  sucursales VALUES (24,335,1117,1,DEFAULT,UBICACION(10.509909,-66.913139,SYSDATE));

-- crear un contrato
INSERT INTO contratos VALUES (2, 5, 25,DEFAULT, RANGO_TIEMPO(TO_DATE('2020-12-08','yyyy-mm-dd'),TO_DATE('2021-11-04','yyyy-mm-dd')), 0.00, null);


--- CREACIONES NO AUTORIZADAS
-- insertar un plan de servicio
INSERT INTO planes_de_servicio VALUES
(17,DEFAULT,RANGO_TIEMPO(SYSDATE,TO_DATE('01/01/2022', 'dd/mm/yyyy')),250,1400,'SEMESTRAL',NULL);
-- insertar un garaje
INSERT INTO garajes VALUES (1,DEFAULT,UBICACION(10.511941,-66.911546,SYSDATE),24,335,1117);

--- UPDATES AUTORIZADOS
-- cambiar el porcentaje descuento de un evento
UPDATE eventos SET porcentaje_descuento=30 WHERE ID = 2;

-- cambiar el nombre de un producto
UPDATE PRODUCTOS SET nombre='galletas light' WHERE ID = 2;

--- UPDATES NO AUTORIZADOS
UPDATE Estados SET nombre='otro nombre' WHERE ID = 2;
UPDATE zonas  SET nombre='otro nombre' WHERE ID = 2;


--- DELETES AUTORIZADOS
DELETE FROM EVENTOS WHERE ID =2;
DELETE FROM detalles WHERE ID =2;


-- DELETES NO AUTORIZADOS
-- borrar un municipio
DELETE FROM MUNICIPIOS WHERE ID =1;
-- borrar un estado
DELETE FROM ESTADOS WHERE ID=2;

