---------- LECTURAS AUTORIZADAS
SELECT * FROM APLICACIONES_DELIVERY;
SELECT * FROM EMPRESAS;
SELECT * FROM SUCURSALES;
SELECT * FROM PRODUCTOS;
SELECT * FROM PEDIDOS;
SELECT * FROM DETALLES;
SELECT * FROM RUTAS;
SELECT * FROM GARAJES;
SELECT * FROM UNIDADES_DE_TRANSPORTE;
SELECT * FROM REGISTRO_DE_MANTENIMIENTO;
SELECT * FROM TIPOS_DE_UNIDADES;
SELECT * FROM USUARIOS;
SELECT * FROM DIRECCIONES;
SELECT * FROM ZONAS;
SELECT * FROM MUNICIPIOS;
SELECT * FROM ESTADOS;


---------- ALGUNAS LECTURAS NO AUTORIZADAS
SELECT * FROM PLANES_DE_SERVICIO;
SELECT * FROM UBICACIONES_APLICABLES;
SELECT * FROM CONTRATOS;
SELECT * FROM ALMACENES;
SELECT * FROM EVENTOS;
SELECT * FROM REGISTROS;

----------- ALGUNAS CREACIONES NO AUTORIZADAS

-- crear un garaje
INSERT INTO garajes VALUES (1,DEFAULT,UBICACION(10.511941,-66.911546,SYSDATE),24,335,1117);

-- insertar una sucursal
INSERT INTO  sucursales VALUES (24,335,1117,1,DEFAULT,UBICACION(10.509909,-66.913139,SYSDATE));

-------------- ALGUNOS UPDATE NO AUTORIZADOS

-- update en tipos de unidades
UPDATE TIPOS_DE_UNIDADES SET velocidad_media = 66 WHERE ID = 3;
--- update en planes de servicio
UPDATE PLANES_DE_SERVICIO SET precio = 100 WHERE ID = 2;

------------- ALGUNOS DELETE NO AUTORIZADOS

-- borrar un estado
DELETE FROM ESTADOS WHERE ID = 2;

-- borrar una direccion
DELETE FROM DIRECCIONES WHERE ID = 13;
