---------- LECTURAS AUTORIZADAS
SELECT * FROM APLICACIONES_DELIVERY;
SELECT * FROM PLANES_DE_SERVICIO;
SELECT * FROM UBICACIONES_APLICABLES;
SELECT * FROM CONTRATOS;
SELECT * FROM EMPRESAS;
SELECT * FROM SUCURSALES;
SELECT * FROM PRODUCTOS;
SELECT * FROM PEDIDOS;
SELECT * FROM DETALLES;
SELECT * FROM RUTAS;
SELECT * FROM GARAJES;
SELECT * FROM UNIDADES_DE_TRANSPORTE;
SELECT * FROM REGISTRO_DE_MANTENIMIENTO;
SELECT * FROM TIPOS_DE_UNIDADES;
SELECT * FROM REGISTROS;
SELECT * FROM USUARIOS;
SELECT * FROM DIRECCIONES;
SELECT * FROM ZONAS;
SELECT * FROM MUNICIPIOS;
SELECT * FROM ESTADOS;

----- LECTURAS NO AUTORIZADAS
SELECT * FROM ALMACENES;
SELECT * FROM EVENTOS;

---- ALGUNAS CREACIONES AUTORIZADAS
-- crear un usuario
CALL INSERTAR_USUARIO('John', null, 'Perez', 'Cor', 'V', 26131344, 'jphnp0@4shared.com','hombre1.jpg');
commit;
-- crear una unidad de transporte
INSERT INTO unidades_de_transporte VALUES (1,17,17,DEFAULT,'NUE-65v','OPERATIVA');
commit;


---- ALGUNAS CREACIONES NO AUTORIZADAS
-- crear una sucursal de empresa
INSERT INTO sucursales VALUES (24,335,1117,1,DEFAULT,UBICACION(10.509909,-66.913139,SYSDATE));


-- crear un nuevo sector de comercio
INSERT INTO SECTORES_DE_COMERCIO VALUES (DEFAULT, 'Nuevo Sector');

---- ALGUNOS UPDATES AUTORIZADOS

-- cambiar precio de plan de servicio
UPDATE PLANES_DE_SERVICIO SET precio = 666 WHERE ID = 1;
commit;

-- cambiar porcentaje de descuento de un contrato
UPDATE CONTRATOS SET porcentaje_descuento = 10 WHERE ID = 1;
commit;

---- ALGUNOS UPDATES NO AUTORIZADOS

-- cambiar el sector de una empresa
UPDATE EMPRESAS SET id_sector = 6 WHERE ID = 1;

-- cambiar el nombre de un producto de un aliado comercial
UPDATE PRODUCTOS SET nombre='galletas de pollo' WHERE ID = 1;

---- DELETE AUTORIZADO

--- borrar un detalle
DELETE FROM DETALLES where ID = 6;

---- DELETES NO AUTORIZADO

--- borrar una aplicacion delivery
DELETE FROM APLICACIONES_DELIVERY where ID = 6;